### ISSUE TITLE
Plugin breaks native upload functionality for plugins

### ISSUE THREAD

**Issue by 1wdtv** [Interfacelab/ilab-media-tools#1]
Plugin is properly working for is intended purpose on S3 images from media library.
However, when installed, it breaks native capability of WP to upload and install a plugin through the normal plugin uploader (not from repository, only via manual upload of a plugin .zip file)

Perhaps it's a permissions issue or that WP is still looking to the native path on site for the .zip file type instead of to S3.

I'll dig into the code later unless you have an immediate "a ha" how to solve.

Here is screenshot.

![upload plugin 1wd tv wordpress](https://cloud.githubusercontent.com/assets/11861749/22513268/5c2e2708-e861-11e6-996c-84ea558617e0.jpg)

Cheers!
spence

**Comment by jawngee** [comment]
Fixed.
