### ISSUE TITLE
Documented environment variable MCLOUD_ASSETS_CDN_BASE has no effect

### ISSUE THREAD

**Issue by rohnjeynolds** [Interfacelab/ilab-media-tools#102]
**Describe the bug**
While trying to use the [documented environment variable](https://help.mediacloud.press/article/68-asset-environment-variables) MCLOUD_ASSETS_CDN_BASE to set the CDN URL for my site, I found that it wasn't respected by Wordpress, and didn't populate the CDN Base URL field in Media Cloud storage settings. This seems to a new problem upgrading from 3.1x to 3.2, but I can't prove it.

Browsing the code base, [I found evidence](https://github.com/Interfacelab/ilab-media-tools/blob/master/config/migrations/migrations.php#L163) that the correct environment variable name is MCLOUD_STORAGE_CDN_BASE. If I set this environment variable, I get the expected result. Is the documentation outdated?

**To Reproduce**
1. Set the environment variable MCLOUD_ASSETS_CDN_BASE, which is documented, to the URL of a CDN.
2. Go to the WP admin page for could storage settings. Note that the CDN Base URL field is blank.
3. Set the envrionment variable MCLOUD_STORAGE_CDN_BASE, which is undocumented, to the URL of a CDN.
4. Go to the WP admin page for cloud storage settings. Note the CDN Base URL field is set correctly.

**Expected behavior**
I'd expect the documented environment variable to control the value.

**Server (please complete the following information)**
- Operating System: Ubuntu
- PHP Version: 7.2
- Web Server: Apache
- Using PHP-FPM? No
- Using WordPress Cron? No

**How did you install the plugin?**
Composer

**Comment by jawngee** [comment]
MCLOUD_ASSETS_CDN_BASE is for the assets feature, not storage.

The correct one for storage is MCLOUD_STORAGE_CDN_BASE

**Comment by jawngee** [comment]
It's documented here:

https://help.mediacloud.press/article/63-cloud-storage-environment-variables
