### ISSUE TITLE
PHP syntax error

### ISSUE THREAD

**Issue by jroquejr** [Interfacelab/ilab-media-tools#105]
**Describe the bug**
That plugin is broken WP installation

**To Reproduce**
1. Plugin when active raises that
2. On activate, he broken.

**Server (please complete the following information)**
- Operating System Linux
- PHP Version 5.4
- Web Server NGinx
- Using PHP-FPM? No
- Using WordPress Cron? No

**How did you install the plugin?**
Wordpress plugin directory

**Additional context**
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) in /home/jornalgr/public_html/wp-content/plugins/ilab-media-tools/classes/Wizard/Config/Section.php on line 74

`class` is a reserved word.
https://github.com/Interfacelab/ilab-media-tools/commit/4568da09fe896aaa957536ba0a59c0b1c59f9589#diff-f98887be20b459c10f331160561df76fR74

**Comment by jawngee** [comment]
On 5.4 you should be getting a startup error that Media Cloud doesn't support 5.4

**Comment by jawngee** [comment]
Fixed

**Comment by jawngee** [comment]
You should really upgrade to PHP 7.x though.  The next version of Media Cloud will drop support for 5.x

**Comment by jroquejr** [comment]
Ok. But the composer requirements can be updated: https://github.com/Interfacelab/ilab-media-tools/blob/master/composer.json

And the checking method too:
https://github.com/Interfacelab/ilab-media-tools/blob/master/ilab-media-tools.php
