### ISSUE TITLE
AWS warnings - open_basedir restriction in effect.

### ISSUE THREAD

**Issue by stuartcusackie** [Interfacelab/ilab-media-tools#117]
**Describe the bug**
`Warning: is_readable(): open_basedir restriction in effect. File(/home/vagrant/.aws/config) is not within the allowed path(s): (/srv/www/:/tmp) in /srv/www/mywebsite.test/current/web/app/plugins/ilab-media-tools/lib/mcloud-aws/aws-sdk-php/src/S3/UseArnRegion/ConfigurationProvider.php on line 134`
`Warning: is_readable(): open_basedir restriction in effect. File(/home/vagrant/.aws/config) is not within the allowed path(s): (/srv/www/:/tmp) in /srv/www/mywebsite.test/current/web/app/plugins/ilab-media-tools/lib/mcloud-aws/aws-sdk-php/src/Retry/ConfigurationProvider.php on line 158
`

This is occurring after updating to the latest version of the plugin on a Roots WordPress installation. I'm not sure if the plugin is to blame or the vagrant box. I've tried destroying my box to no effect.

wp-admin becomes inaccessible due to the warnings affecting the header ouput.

**To Reproduce**
Visit any page

**Server (please complete the following information)**
- Operating System: Windows
- PHP Version: 7.4
- Web Server: Vagrant
- Using PHP-FPM: Yes
- Using WordPress Cron? No

**How did you install the plugin?**
Composer

**Comment by jawngee** [comment]
Edit your `/etc/php/4.7/fpm/pool.d/wordpress.conf` and add your tmp directory to the `php_admin_value[open_basedir]`, for example:

``php_admin_value[open_basedir] = /srv/www/:/tmp:/home/vagrant/bin:/home/vagrant/.aws``

Closing because this isn't a bug, your install is being overly restrictive for no good reason.
