### ISSUE TITLE
Generating lots of slow queries

### ISSUE THREAD

**Issue by gtu-myowin** [Interfacelab/ilab-media-tools#119]
**Describe the bug**
My website got a lot slower after installing this plugin. So, I went ahead tested with “Query Monitor” plugin and found out Media Cloud plugin is making a lot of slow queries. Here is one the same queries

**To Reproduce**
1. Install "Query Monitor" plugin
2. Go to website (with post loop) home page
3. You will see a lot of slow queries

Here is the error code.

```
attachment_url_to_postid()
wp-includes/media.php:4643
MediaCloud\P\T\S\StorageTool->filterContent()
wp-content/plugins/ilab-media-tools/classes/Tools/Storage/StorageTool.php:2294
apply_filters('the_content')
wp-includes/plugin.php:206
the_content()
wp-includes/post-template.php:253
load_template('wp-content/themes/mwd/template-parts/content-page.php')
wp-includes/template.php:732
locate_template()
wp-includes/template.php:676
get_template_part('template-parts/content','page')
wp-includes/general-template.php:204
```

See this screenshot for more information » https://drive.google.com/file/d/1x4U2o4UNJsrXFPNeWtbUu5Osud0ZMX6z/view?usp=sharing

It even caused Gateway time-out error » https://drive.google.com/file/d/1cfE-oVTTw-nOrXVAUIoP_Jm7R5wu0vK9/view?usp=sharing

**Comment by JonHendershot** [comment]
I'm having seemingly related issues with this plugin. [Trace logs](https://prnt.sc/1u8810r) seem to show it hooking into ACF Pro functions and causing pages to take upwards of 30s to load. This plugin is very untenable for this reason, IMO. I'll be spending some time working to remove it from our system entirely as this issue has gone unacknowledged for nearly a year now.
