### ISSUE TITLE
Images hit 403 error (AWS S3 + Imgix)

### ISSUE THREAD

**Issue by elliottmangham** [Interfacelab/ilab-media-tools#121]
**Describe the bug**
Images are uploading to AWS S3 successfully, the File URL is an Imgix link, the cloud icon shows and all of the tests in Media Cloud work fine. However, the images are hitting a 403.

See example: https://designerdram.imgix.net/2020/12/shutterstock_761907991-scaled.jpg?auto=compress%2Cformat&ixlib=php-3.3.0

**Screenshots**
See how images are not showing, despite having the cloud icon. The File URL is on Imgix, but I get a 403 error:
![Screenshot 2020-12-02 200111](https://user-images.githubusercontent.com/12933804/100924896-29470580-34d9-11eb-8894-1edc3c2a991b.png)

**Server (please complete the following information)**
- Operating System: Windows 10
- PHP Version: 7.3
- Web Server: Apache (20i.com)
- Using PHP-FPM? Yes.
- Using WordPress Cron? Unsure.

**How did you install the plugin?**
Installed on my local environment (Local by Flywheel) and deployed it to the server and added settings in there.

Thank you

**Comment by jawngee** [comment]
https://support.imgix.com/hc/en-us/articles/360000178806-HTTP-Status-codes#____forbidden

**Comment by elliottmangham** [comment]
@jawngee, I already read those docs but since they are vague I haven't been able to resolve. As a premium plugin do you not provide support/advice?

**Comment by jawngee** [comment]
If you have a tech support question, you should open a ticket here: https://support.mediacloud.press/ticket/new

Github is for actual bugs.  This isn't a bug.  You've most likely not configured your IAM policy correctly or you've turned secure URLs on in your imgix source but not turned it on in Media Cloud.

**Comment by elliottmangham** [comment]
Understood — Boss.
