### ISSUE TITLE
Media Cloud not supported with PHP 8.0

### ISSUE THREAD

**Issue by NgHuuAn** [Interfacelab/ilab-media-tools#122]
**Not sure if media cloud compatible with PHP 8**

I want to try the php8.0 version for my wordpress websites, we have demo on 1 new sites, everything is fine. However, the Media Cloud plugin is not working. We have temporarily disabled the test site and hope that you have the latest updates for PHP 8.0

1. Go to Add New Plugin
2. Search Media Cloud
3. Click on Install Now

Installation failed: There has been a critical error on this website. Please check your site admin email inbox for instructions.Learn more about debugging in WordPress.

![image](https://user-images.githubusercontent.com/31845795/101612075-d4594100-3a3c-11eb-916c-b2144abc1cb3.png)

We check the Apache log files: 

[Wed Dec 09 16:25:00.722568 2020] [proxy_fcgi:error] [pid 63703] [client 113.161read(): Argument #2 ($length) must be greater than 0 in /var/www/*.cwp-admin/includes/class-pclzip.php(4212): fread()\n#1 /var/www/*/wp-admin/includes/class-pclzip.php(811): PclZip->privExtractt()\n#4 /var/www/*/wp-admin/includes/file.php(1476): _unzip_filenzip_file()\n#6 /var/www/*/wp-admin/includes/class-wp-upgrader.pclass-plugin-upgrader.php(137): WP_Upgrader->run()\n#8 /var/www/*/wp-admin/plugin-install.php?s=Media%20cloud&tab=search&type=term

**Server (please complete the following information)**
- Operating System: Ubuntu 20.04
- PHP Version: 8.0
- Web Server: Nginx reverse Apache
- Using PHP-FPM? Yes
- Using WordPress Cron? No

**Comment by jawngee** [comment]
The problem isn't Media Cloud, the problem is clearly stated in the log:

    Argument #2 ($length) must be greater than 0 in /var/www/.cwp-admin/includes/class-pclzip.php: fread()

It looks like you got a bad download or something.  I don't know what .cwp-admin is so I can't tell you, but I can tell you it doesn't have anything to do with Media Cloud.

Two of our test systems run PHP 8 just fine.

**Comment by jawngee** [comment]
Apparently cwp-admin is CWP Web Panel, so maybe bring the issue up with them since the error is being generated from their code.  It's coincidental that you were updating Media Cloud when it happened.

**Comment by jawngee** [comment]
Also, I think it's a bit premature to be running WordPress on PHP 8.  You're creating headaches for yourself until the rest of ecosystem gets up to speed.

**Comment by NgHuuAn** [comment]
> Apparently cwp-admin is CWP Web Panel, so maybe bring the issue up with them since the error is being generated from their code. It's coincidental that you were updating Media Cloud when it happened.

It's strange about the above error when on the server there isn't any control panel, everything is used via the command line.

I installed a PHP 7.4 on the same server and changed some configurations for the website to run on 7.4 and everything is fine but thanks for your comments. We will investigate more about this problem for our sites.
