### ISSUE TITLE
Plugin Causes Undefined Offset Error in wp-includes/media.php

### ISSUE THREAD

**Issue by mattcdavis1** [Interfacelab/ilab-media-tools#124]
**Describe the bug**
Activating the plugin generates PHP errors in the wp-includes/media.php file

**To Reproduce**
Activate plugin

**Expected behavior**
No new PHP errors

**Screenshots**
https://www.screencast.com/t/KngS4bkyP

**Server (please complete the following information)**
- Operating System: linux
- PHP Version: 7.4
- Web Server: Apache
- Using PHP-FPM? Yes
- Using WordPress Cron? No

**How did you install the plugin?**
Did you install via composer, a git checkout, wordpress.org, freemius? wordpress console

**Additional context**
Errors go away as soon as plugin is deactivated so the plugin is definitely the issue. It looks like incorrect parameters are being passed to image_get_intermediate_size and other media functions.

**Comment by jawngee** [comment]
What other plugins do you have activated at the same time?  If Media Cloud is the only plugin activated do you receive that error?

Also which WordPress version and which version of Media Cloud

**Comment by mattcdavis1** [comment]
[Here's a screenshot](https://www.screencast.com/t/J8hHpWXt) of the plugins. I had to enable advanced custom fields for the page to work but i disabled all the others.

Wordpress version is 5.6 and Media Cloud is 4.1.14
