### ISSUE TITLE
Allow manual cropping of all images

### ISSUE THREAD

**Issue by JulienMelissas** [Interfacelab/ilab-media-tools#13]
This is more of a feature request/idea to see if there is some interest in making it so that maybe we can use the awesome cropping tool for images that aren't automatically cropped by WordPress? I think it would be great to allow clients/users the ability to crop all images as they see fit. Somewhat like [this plugin](https://wordpress.org/plugins/manual-image-crop/), which I've used many times before.

Anyone else interested in this? I'm going to try and take a look today to see how hard it would be to pull off with Imgix. Not really sure how I would pull this off with just S3, but that doesn't fit my use case so I was thinking Imgix would be a requirement.

**Comment by jawngee** [comment]
You can do that now with the plugin, unless I'm misunderstanding.  It'll crop local files, any size that is specified in your theme + wordpress plugins.

**Comment by jawngee** [comment]
Unless you mean the ability to arbitrarily crop an image?

**Comment by JulienMelissas** [comment]
Yeah, honestly that's kind of what I was thinking... that functionality is more inline with the "Manual Image Crop" plugin I linked to. I know with Imgix it's possible to pull off manual cropping, I just haven't had too much time to see how difficult it might be to pull of within this plugin's edit tool.
