### ISSUE TITLE
Huge performance leak | 100's of slow queries detected on each request

### ISSUE THREAD

**Issue by luissimo** [Interfacelab/ilab-media-tools#131]
Hi,

After multiple crashes of our production E-commerce environment due to php worker limit issues we discovered through New Relic that Media Cloud is the issue. It does a lot of sql queries which in their return occupy the php workers.

We are running on the latest woocommerce(v5.1.0)/wordpress(v.5.7.0)/media cloud  premium version(v4.2.8) as of today (march 16th 2021).

**------------- EXPLANATION -------------**
When entering any non-cached page it fires 100's/1000's (literally) of these queries which **greatly disrupt performance**.
`select * from wp_mcloud_task_data where complete != 1 and taskId = 2323 order by id asc limit 10`

Example is adding a product to the cart from a product page or simply entering any product loop page or single product page with parameters in the url (eg. url containing Google Analytics tracking parameters or filters)

**--- Stack trace**

```
wp-db.php in wpdb→query at line 2701

TaskData.php in wpdb→get_results at line 169

Task.php in MediaCloud\Plugin\Tasks\TaskData::dataForTask at line 416

Task.php in MediaCloud\Plugin\Tasks\Task→__construct at line 1126

TaskManager.php in MediaCloud\Plugin\Tasks\Task::runningTasks at line 56

TaskManager.php in MediaCloud\Plugin\Tasks\TaskManager→__construct at line 66

ToolsManager.php in MediaCloud\Plugin\Tasks\TaskManager::instance at line 327

ilab-media-tools.php in MediaCloud\Plugin\Tools\ToolsManager::Boot at line 201

class-wp-hook.php in {closure} at line 294

wp-settings.php in do_action at line 423
```

**Second stack trace**

```
wp-db.php in wpdb→query at line 2587

TaskData.php in wpdb→get_var at line 189

Task.php in MediaCloud\Plugin\Tasks\TaskData::dataCountForTask at line 415

Task.php in MediaCloud\Plugin\Tasks\Task→__construct at line 1126

TaskManager.php in MediaCloud\Plugin\Tasks\Task::runningTasks at line 56

TaskManager.php in MediaCloud\Plugin\Tasks\TaskManager→__construct at line 66

ToolsManager.php in MediaCloud\Plugin\Tasks\TaskManager::instance at line 327

ilab-media-tools.php in MediaCloud\Plugin\Tools\ToolsManager::Boot at line 201

class-wp-hook.php in {closure} at line 294

wp-settings.php in do_action at line 423
```

**-------------------------------------**

When the page is already cached or it contains no parameters the query fires only three times which is reasonable.

**Comment by jawngee** [comment]
Go into WordPress admin -> Media Cloud -> Task Manager.  Click on **Reset All Task Data**.

Then turn off push assets if you are using that.  You should be using pull assets instead.  Push is for very narrow use cases.

Then also turn off queue deletes in cloud storage settings.

The only way it's firing 1000's of queries is if you have 1000's of tasks waiting to be run which means you have either of those options enabled when you probably shouldn't because they're for pretty specific use cases.

**Comment by jawngee** [comment]
I will add a condition that only triggers the task manager if you are logged into the admin, so in the meantime, you can change line 1115 of `classes/Tasks/Task.php` to:

```php
	/**
	 * The currently running tasks
	 *
	 * @return Task[]
	 * @throws \Exception
	 */
	public static function runningTasks() {
		if (!is_admin()) {
			return [];
		}

		global $wpdb;

		$results = [];

		$table = static::table();
		$state = self::STATE_COMPLETE;
		$rows = $wpdb->get_results("select * from {$table} where state < {$state} order by id desc");
		foreach($rows as $row) {
			$taskClass = TaskManager::taskClass($row->type);
			if (!empty($taskClass)) {
				$results[] = new $taskClass($row);
			}
		}

		return $results;
	}
```

**Comment by jawngee** [comment]
But the condition is def happening because you have a bajillion tasks waiting to run.

**Comment by luissimo** [comment]
Appreciate the quick response very much.

I have deleted the tasks running, you were right there were a lot of stale tasks. We are not using push/pull assets but we do have Queue deletes enabled. So that seems to have caused this somehow.

Any idea when you will release an update of the above mentioned code change? Then we can decide to change it ourselves or just wait it out while continuing monitoring the task manager.

**Comment by jawngee** [comment]
I'm working on a few other fixes, so I'll include this in the next batch.  Likely not until late this week or next Monday.

Glad it cleaned it up!  I'll also look into why the delete task fails so much.  We get a number of support tickets for it but cannot replicate it.

**Comment by luissimo** [comment]
Good to hear. We will wait for that then. Keep up the good work.

**Comment by hubertnguyen** [comment]
> I will add a condition that only triggers the task manager if you are logged into the admin

If I may suggest, perhaps you could even trigger it only if the admin is in the media cloud "tasks" page.

**Comment by jawngee** [comment]
> > I will add a condition that only triggers the task manager if you are logged into the admin
> 
> If I may suggest, perhaps you could even trigger it only if the admin is in the media cloud "tasks" page.

The only problem with that is if people don't have WP_CRON setup correctly, which most don't.  We have to cover the least common denominator, which for WordPress is a very very very very very low bar.  

Trust me, we've been through so much shit with running background tasks over the years.  

The new update will be out tomorrow that addresses this issue.
