### ISSUE TITLE
Remove console hello/t message

### ISSUE THREAD

**Issue by DavidMillington-CD** [Interfacelab/ilab-media-tools#136]
If you open the WordPress admin while the Media Cloud plugin is enabled then you get a console message _hello/t_ sent from mcloud-admin.js.  Inspecting the file I can see console.log("//hello/t/".trimCharsLeft("/")).  It's a very minor thing but I don't think it should be there.

Media Cloud Premium 4.2.11

**Comment by jawngee** [comment]
wait until you see what happens when you do direct uploads!

this was resolved in the update that is currently in testing.  closing.
