### ISSUE TITLE
Can't use with new Digital Ocean Space San Francisco 3 region.

### ISSUE THREAD

**Issue by regiside** [Interfacelab/ilab-media-tools#137]
Digital Ocean is currently only offering their third location in San Francisco. This option is not in the drop down list of the setup wizard. I just realized I can enter the subdomain manually on the provider settings page, but I have to cancel the wizard to get there. Could you add SFO3 to the list, and/or create an "other" option in the drop down box, for the edge cases where there's a new region that hasn't been added to the plugin yet?

**Comment by jawngee** [comment]
Fixed in latest.  Likely won't add that field to the wizard though, at least not anytime soon.
