### ISSUE TITLE
Fatal Error on Image Upload

### ISSUE THREAD

**Issue by BoxMediaUK** [Interfacelab/ilab-media-tools#14]
Fatal error: Uncaught Error: Call to undefined function mime_content_type() in /home/domain/public_html/wp-content/plugins/ilab-media-tools/classes/tools/s3/ilab-media-s3-tool.php:785 Stack trace: #0 /home/domain/public_html/wp-content/plugins/ilab-media-tools/classes/tools/s3/ilab-media-s3-tool.php(548): ILabMediaS3Tool->processFile(Object(ILAB_Aws\S3\S3MultiRegionClient), '/home/domain', '2017/09/female-...', Array, 3105) #1 /home/domain/public_html/wp-includes/class-wp-hook.php(298): ILabMediaS3Tool->updateAttachmentMetadata(Array, 3105) #2 /home/domain/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) #3 /home/domain/public_html/wp-includes/post.php(5013): apply_filters('wp_update_attac...', Array, 3105) #4 /home/domain/public_html/wp-admin/includes/media.php(383): wp_update_attachment_metadata(3105, Array) #5 /home/domain/public_html/wp-admin/async-upload.php(91): media_handle_upload('async-upload', 0) #6 {main} in /home/domain/public_html/wp-content/plugins/ilab-media-tools/classes/tools/s3/ilab-media-s3-tool.php on line 785

**Comment by jawngee** [comment]
http://php.net/manual/en/function.mime-content-type.php

**Comment by jawngee** [comment]
That's a builtin php function.

What version of PHP are you using?

**Comment by jawngee** [comment]
Fixed in 1.5.3 (commit 035850c53021e888309aa06da2ecd2fcd60b517a specifically)

**Comment by BoxMediaUK** [comment]
For your information, its on the same server as three of my other sites all working perfectly with your solution. I'll give the update a try and let you know..
