### ISSUE TITLE
Loading Admin Block Editor Styles On Frontend

### ISSUE THREAD

**Issue by DavidMillington-CD** [Interfacelab/ilab-media-tools#145]
**Describe the bug**
The admin Gutenberg block styles are being loaded on the front end.  I first noticed it today with MediaCloud Pro 4.2.20 and I just updated to 4.2.26 and the problem is still there.

**To Reproduce**
1. Install MediaCloud Pro plugin and activate it.
2. Open front end page.
3. View source
4. View the header section to see admin stylesheets tags that should not be on the front end:

> wp-components-css - /wp-includes/css/dist/components/style.min.css
> wp-block-editor-css - /wp-includes/css/dist/block-editor/style.min.css
> wp-nux-css - /wp-includes/css/dist/nux/style.min.css
> wp-editor-css - /wp-includes/css/dist/editor/style.min.css
> mux_video_block_style-css - /wp-content/plugins/ilab-media-tools-premium/public/blocks/mediacloud-mux.blocks.style.css

**Expected behavior**
Should be able to load front end without having admin block editor stylesheets included.

**Additional context**
Video Encoding is turned off.

Took me ages to track this down.  The lines only vanished when I removed the MediaCloud plugin so I knew this was were to focus.  I managed to pin point it to `/wp-content/plugins/ilab-media-tools-premium/classes/Tools/Video/Driver/Mux/MuxTool.php`.  These lines inside initBlocks() are the culprits:

- wp_register_style('mux_video_block_style', ILAB_BLOCKS_URL.'mediacloud-mux.blocks.style.css', ['wp-editor'], null);
- wp_register_script('mux_video_block_js',ILAB_BLOCKS_URL.'mediacloud-mux.blocks.js', ['wp-blocks', 'wp-i18n', 'wp-element', 'wp-editor'], null, true);
- wp_register_style('mux_video_block_editor_style', ILAB_BLOCKS_URL.'mediacloud-mux.blocks.editor.css', ['wp-edit-blocks'], null);

Not only are the outputting admin styles on the front end but they are running even though Video Encoding is turned off.

Using the normal wp_dequeue_style() method in functions.php does not work to remove them.  For now I've commented out these lines in the MediaCloud plugin and will keep having to do that through each update until you fix it.

**Comment by jawngee** [comment]
4.3.0 completely overhauls all of this stuff.  This is one issue I've tackled already.  I'm going to keep this issue open until 4.3.0 is released though, in case others are looking for a solution.

**Comment by regiside** [comment]
Thanks David, I was having the same issue and your solution helped. Seems like development on the plugin has halted. :(
