### ISSUE TITLE
2.0.4 Resizes Images For Some Reason

### ISSUE THREAD

**Issue by curranabell** [Interfacelab/ilab-media-tools#15]
Hi,

Just thought I would let you know that the 2.0.4 update somehow refactored all my images to different image sizes for some reason and I am not sure why.

Just thought I would let you know.

Thanks for such an awesome plugin and continuing the new realeases on a regular.

You make my life 100x easier not having to use the S3 offload plugin.

Thanks!

**Comment by jawngee** [comment]
Are you using Imgix?

**Comment by jawngee** [comment]
Also, are these images embedded in posts or used elsewhere in a theme?

PS. Thanks for the great review!

**Comment by jawngee** [comment]
I'm wondering if you are seeing srcset in action.  That was broken in versions previous to 2.0.4.

https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/

**Comment by jawngee** [comment]
Hello? :)

**Comment by curranabell** [comment]
Hey apologies for the terribly late reply! I haven't been on github in so long sorry about that. I think this is fixed in the new versions! Thank you!
