### ISSUE TITLE
Player settings and mux_video shortcode support

### ISSUE THREAD

**Issue by steveadamsfixedit** [Interfacelab/ilab-media-tools#152]
**Describe the bug**
I'm having difficulty getting mux encoded videos to display and play...I'm not seeing any "3 options" in the Media Cloud -> Settings -> Video Encoding -> Player Settings. Only one option for "additional CSS".

I've tried manually adding the [mux_video] short code as suggested here:

https://support.mediacloud.press/articles/advanced-usage/theme-integration/video-player-shortcode

The documentation here is extremely weak. Where would I get the ID variable? The asset ID in Mux is not an integer and the short code itself doesn't appear to load a video player?

I've tried using a the MUX playback ID, the MUX asset ID, the Google Cloud Bucket asset ID and the media library asset ID...no go on all counts

**Expected behavior**
I'd expected more extensive player settings options as indicated in the docuementation

**Server (please complete the following information)**
- Ubuntu 20.04 on Google Cloud VM
- php 7.4.3
- apache 2.4
- with PHP-FPM
- NOT USING WordPress Cron
- - WP version 5.6.4

**How did you install the plugin?**
Installed the plugin through the WP Add Plugin backend

**Comment by jawngee** [comment]
You're using the free version?  There is no player in the free version, the free version simply add hls.js which adds support to for HLS video streams to the html5 <video> element.  The video.js player is in the pro version.

**Comment by jawngee** [comment]
And with the pro version there isn't really a way to add a shortcode manually because the ID is in the database and not exposed in any UI elements.
