### ISSUE TITLE
No Support!

### ISSUE THREAD

**Issue by steveadamsfixedit** [Interfacelab/ilab-media-tools#163]
I've been creating support requests on support.mediacloud.press and received absolutely no reply for over two months...IS THERE ANYONE THERE?

**Comment by JulienMelissas** [comment]
I have also asked a few pre-sales questions with no response.

**Comment by insanity54** [comment]
The discourse link on the Wordpress forum is broken

https://wordpress.org/support/topic/no-longer-providing-support-on-these-forums/

**Comment by jssellars** [comment]
Lost in the void. Same here, no response.

**Comment by ChristinaSW** [comment]
Same problem here and I'm paying monthly for the pro version!

**Comment by allancrabtree** [comment]
Same problem here. Waiting for months.

**Comment by gouku** [comment]
@jawngee is this project still being actively maintained? as a subscription service I got no ticket support for months.

**Comment by JulienMelissas** [comment]
Hate to creep here, but they're [active on GitHub](https://github.com/directus/directus/issues/11177) which means they're actively ignoring us 🤷

**Comment by gouku** [comment]
@JulienMelissas I've stopped the sub and migrated to WP Offload Media. so far so good.

**Comment by abazeed** [comment]
Same here, I can't login to the support portal to open a ticket, and no one replies on the live chat!!

**Comment by stephenfeather** [comment]
@JulienMelissas How painful was the transition?


> @JulienMelissas I've stopped the sub and migrated to WP Offload Media. so far so good.
> 
> It seems the author got a new full-time job and will no longer maintain this plugin.

**Comment by JulienMelissas** [comment]
@stephenfeather - I think you might want to ask @gouku, we haven't had the opportunity to migrate off yet. Would love a guide or any steps taken since at some point I imagine we'll have to do it 😄
