### ISSUE TITLE
Where to get billing support?

### ISSUE THREAD

**Issue by heyitsbryanm** [Interfacelab/ilab-media-tools#166]
**Describe the bug**
This is not a bug report for this repo. Instead, there doesn't appear to be any way of getting any support for the service/product. The previous discord link for getting support is broken.

**To Reproduce**

1. Go to the plugin page: https://wordpress.org/support/plugin/ilab-media-tools/
2. Click on this stickied topic: https://wordpress.org/support/topic/no-longer-providing-support-on-these-forums/
3. Click the discourse forum link: https://discourse.interfacelab.io/
4. Leads to 404

**Expected behavior**
A working link to discourse or a place to get billing support.

**Comment by jssellars** [comment]
Check with Freemius, they're the ones that billing flows through. They are at least a little bit more responsive. If you don't hear from them, blow up Freemius's twitter account, I at least got a response from that.

**Comment by heyitsbryanm** [comment]
Thanks!

**Comment by mattneal-stafflink** [comment]
I've honestly moved away from this plugin purely for the lack of support. I get more support from dead open source projects.
