### ISSUE TITLE
Backblaze's certificate has expired

### ISSUE THREAD

**Issue by BeiMingXie-K** [Interfacelab/ilab-media-tools#178]
The certificate for backblaze has expired, causing a fatal error in enabling.Before that, I contacted the customer service of B2, but he only gave me the certificate, but I don't know where this certificate should be placed. I hope you can help update it. Thank you!

**Comment by jawngee** [comment]
You should contact them again and ask them what to do with it.  We don't include any certs in Media Cloud.
