### ISSUE TITLE
Previously uploaded images and On the Fly image generation

### ISSUE THREAD

**Issue by kaisermann** [Interfacelab/ilab-media-tools#18]
1) I was using w3tc for the s3 upload feature (yes...) and all my files prior to this moment are already on my s3. Is there anyway I can force to use the CDN URL?

2) Is it possible to make Media Tools work with some king of on-the-fly image size generation plugin/library (like aq_resize, [Fly Image Resizer](https://github.com/junaidbhura/fly-dynamic-image-resizer) or [Image Processing Queue](https://wordpress.org/plugins/image-processing-queue))

Btw, awesome plugin, thanks!

**Comment by jawngee** [comment]
As for #1, not easily.

As for #2, use Imgix. ;). Once those files are on S3 there is no other way to do it.
