### ISSUE TITLE
4.4.4 caused site outage

### ISSUE THREAD

**Issue by simshaun** [Interfacelab/ilab-media-tools#185]
**Describe the bug**
After upgrading to 4.4.4, the site went dead with the following error:

```
Fatal error: Uncaught Error: Class 'MediaCloud\Plugin\Tools\ToolsManager' not found in (..trimmed..)wp-content/plugins/ilab-media-tools/ilab-media-tools.php:206
```

**Server (please complete the following information)**
- Operating System - Debian 10
- PHP 7.4.7
- Web Server - Apache
- Using PHP-FPM? Yes
- Using WordPress Cron? No

**How did you install the plugin?**
wordpress.org

**Comment by jawngee** [comment]
Delete and reinstall.  Because of the plugin size on some servers it can fail during the update process.

**Comment by jawngee** [comment]
Actually disregard.  Looking into the issue.

**Comment by simshaun** [comment]
> Delete and reinstall. Because of the plugin size on some servers it can fail during the update process.

Tried that just to be sure and no dice.

**Comment by simshaun** [comment]
Can confirm 4.4.5 is working. 👍 

Thanks for a quick fix.

**Comment by jawngee** [comment]
Fixed now.
