### ISSUE TITLE
video is not showing on website with cloudflare r2

### ISSUE THREAD

**Issue by armanism24** [Interfacelab/ilab-media-tools#190]
**Describe the bug**
I have uploaded a video using this plugin with Cloudflare R2 configured and I have embedded this though elementor but when I visit my website video is not showing/playing. but through direct URL (direct video URL) it is showing.
**To Reproduce**
1. Go to https://web.milieuxproperty.com/
2. See the header video is not loading

**Expected behavior**
It should be showing a video when you visit the website.

**Screenshots**

![see this](https://i.ibb.co/QJPY7SW/Screenshot-2022-10-27-at-4-02-25-AM.png)

**Server (please complete the following information)**
- Operating System - CentOS7
- PHP Version - PHP 7.4
- Web Server - apache 2
- Using PHP-FPM? yes
- Using WordPress Cron? - yes

**How did you install the plugin?**
I have installed this from wordpress.org
**Additional context**
nothing extra

**Comment by jawngee** [comment]
I see a video.

![Screenshot of Safari (10-27-22, 8-24-36 AM)](https://user-images.githubusercontent.com/44449/198169319-92f32639-d24f-4717-aa37-c104f9a148be.png)

You probably shouldn't be doing it this way but that has nothing to do with Media Cloud.

**Comment by jawngee** [comment]
Your video is 84 megabytes btw, you might want to re-encode that to something considerably smaller or use HLS via mux.com.
