### ISSUE TITLE
Make admin notice dismissible

### ISSUE THREAD

**Issue by 1wdtv** [Interfacelab/ilab-media-tools#2]
![plugins 1wd tv wordpress](https://cloud.githubusercontent.com/assets/11861749/22519963/1a6366aa-e878-11e6-9cea-b468f69e906d.jpg)
Don't need/want to use image processing. 
Would be nice to make notice dismissible.

https://github.com/Interfacelab/ilab-media-tools/blob/master/classes/tools/imgix/ilab-media-imgix-tool.php

Starting on line 50:  To start using Imgix, you will need to...

**Comment by jawngee** [comment]
Fixed in 68fac28013ea372f7a0bd896c604bbf27299357b
