### ISSUE TITLE
Critical error "Uncaught Error: Call to undefined function trailingslashit()" after updating plugin to 4.5.15

### ISSUE THREAD

**Issue by relaxdd** [Interfacelab/ilab-media-tools#203]
**Server (please complete the following information)**
- Operating System
- PHP Version => 7.4
- Web Server => OpenServer
- Using PHP-FPM? => No
- Using WordPress Cron? => No
- WordPress version 6.1.1

**How did you install the plugin?**
Did you install via composer, a git checkout, wordpress.org, freemius? => No

**Comment by jawngee** [comment]
Did it say what file or line?  `trailingslashit` is a wordpress function so it should always be available, unless you are trying to run this code outside of wordpress somehow.

**Comment by jawngee** [comment]
Yeah 4.5.15 doesn't even use `trailingslashit` in any of its changes (see https://github.com/Interfacelab/ilab-media-tools/commit/0326322fadc816dace9401b5896aa2defa2ca2b7).

4.5.14 changes do have the use of `trailingslashit` in one place in the changeset but its in a class that has already been using that function for six years now.

My guess is that something is either messed up with your wordpress install, or if you updated the plugin from wordpress.org or freemius, maybe the plugin didn't install 100%.  I'd delete the plugin and reinstall it again.

I'm going to close this for now, but if you can get me a file and line number to see where the error is, I'll take a look at it.

**Comment by jawngee** [comment]
@relaxdd did you get it sorted?

**Comment by relaxdd** [comment]
@jawngee yes, most likely the problem was that the plugin was not updated correctly
