### ISSUE TITLE
installing premium version via composer: an ETA ?

### ISSUE THREAD

**Issue by pixeline** [Interfacelab/ilab-media-tools#206]
The readme mentions that we can soon use composer to update the premium version fo the plugin.

> For the pro version, installing via composer won't be available until the end of July.

Not sure which year that July is for,  I was wondering if you could perhaps give us an ETA ?

Thank you!

Alex.

**Comment by jawngee** [comment]
You can install the premium version through composer right now.

Log into your freemius account, go to the downloads section and click on the composer button.  A help window will popup with instructions.

￼

**Comment by jawngee** [comment]
![SCR-20221212-vxk](https://user-images.githubusercontent.com/44449/207093022-2ca1e899-3dcc-4780-92c5-9261144f6150.png)
