### ISSUE TITLE
Path of CDN domain is stripped when in private mode (and credential are sent in admin)

### ISSUE THREAD

**Issue by brusco77** [Interfacelab/ilab-media-tools#210]
**Problem**
When "Upload Privacy ACL" is private, path part of CDN based url is stripped 
Furthermore, credential are sent even if not needed

**To Reproduce**
Go to media cloud settings in your wp
admin.php?page=media-cloud-settings
choose "private" as upload privacy acl

in upload path insert the default path @{date:Y/m} or leave blank

insert in CDN base url a path like 
https://something.com/content/myuploads

when we upload an image and visit admin or frontend, content/myuploads is stripped and images
are like https://something.com/2023/05/file.jpg

furthermore, when we visit images in frontend everything is fine,
but in media->library they have a path like
https://something.com/2023/05/file.jpg?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-..](https://www.power-talentagency.it/content/uploads/2023/05/test.png?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-..)..

since lately AWS dediced to avoid ACL 
https://aws.amazon.com/it/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/

it would be nice to have the possibility to upload files without specifying acl

**Expected behavior**
We expect that the path is not stripped and to be able not to specify ACL and not having this part
?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&

**Server (please complete the following information)**
PHP Version 7.4 PHP-FPM
Web Server Nginx

**How did you install the plugin?**
just downloaded from web and uploaded it

thank you

**Comment by jawngee** [comment]
We don't support paths in the CDN name because of the way WordPress works.  You should setup your upload path to match whatever scheme you want instead.

As for the ACL, that's not an easy change considering it'd potentially impact 9000+ websites so it's not likely something I'll attempt to change anytime soon.
