### ISSUE TITLE
Issues after installing PHP 8.2 and MediaCloud

### ISSUE THREAD

**Issue by ceoseoinc** [Interfacelab/ilab-media-tools#215]
BUG REPORT AND ISSUES

Overview:
Upon upgrading from PHP 7.4 to PHP 8.2, MediaCloud displays erratic behavior with several functionalities malfunctioning. Preliminary analysis suggests a potential "TypeError".

Issues Observed Post-Update:

Specific image folders within WordPress go missing.
The 'CloudTasks' feature is non-functional during image/media synchronization.
The 'Contact Us' page experiences a complete crash.
Multiple errors have been identified in the debug/error logs.
Steps to Replicate the Behavior:

Transition to PHP 8.2.
Initiate media synchronization via CloudTasks.
Investigate the homepage for absent images, specifically the SEOinc logo located at the top left.
Expected Outcome:
While MediaCloud is fully compatible with PHP 7.4, the same is not observed for PHP 8.2 and subsequent versions.

Visual Evidence:
Relevant screenshots would be beneficial for a comprehensive understanding.

Server Details:

Hosting Service: wpengine
PHP Version: 8.2 Ningix
WordPress Cron Utilization: Not sure but currently using EasyCron
Plugin Installation Method:
The plugin was procured as a zip file and was subsequently installed via the 'Add New Plugins' option in WordPress.

Supplementary Information:
Efforts have been made to connect with the support team directly, but the response remains awaited.
[ErrorLogs.txt](https://github.com/Interfacelab/ilab-media-tools/files/12385975/ErrorLogs.txt)

**Comment by jawngee** [comment]
We don't support 8.2.  It's impossible for us to support 8.2 and support 7.4 at the same time (68% of our users use 7.x).

All of our test machines and dev machines use 8.1 with no issue though.  You will get INFO notices in your logs about return and argument types, but they are just INFO notices, they aren't necessarily errors.  If its breaking your site then your configuration for php's error handling is probably not correct (assuming this is a production environment).  

WordPress itself only has beta support for 8.2.

And, as far as I know, WPEngine is extending support for 7.4 for the rest of this year (https://wpengine.com/blog/offering-all-customers-extended-support-php-7-4/), but you should use 8.0 or 8.1 which only has the above INFO issues.

**Comment by ceoseoinc** [comment]
Would this be advisable, from WPengine support. What direction would you suggest?

We would recommend making a fresh copy to STG or DEV to troubleshoot further. The production site shows some files not verifying against checksums for WordPress core. STG or DEV can be used to reinstall core files. After that, the plugin should be checked to determine if the issue still persists on PHP 8.2.

Warning: File doesn't verify against checksum: wp-cron.php
Warning: File doesn't verify against checksum: wp-settings.php
Warning: File doesn't verify against checksum: wp-trackback.php
Error: WordPress installation doesn't verify against checksums.


The cause of the issue isn't known at the moment. It definitely helps that you've been able to get everything working with Local and that Mediacloud has been able to confirm their plugin working on PHP 8.2. The best thing would be to rule out possible culprits by making a new copy to staging or dev. That way, this can be troubleshoot further without affecting the live site.

The WordPress core files can be safely reinstalled there. That's the first thing I would recommend because of how you explained the issue. WordPress core and the must-use plugins are the potential differences between WPE and Local. They're probably not the only ones, but that's a start. We can reinstall core files in support chat any time.



Best Regards,
***@***.***

[EO Inc.]<https://t.sidekickopen08.com/s3t/c/5/f18dQhb0S7kv8cVX5FW29Hn-t59hl3kW7_k2842Pyh5PN1G6-wcvLTt7Vsgcjk2bzNJKf8C1-HG01?te=W3R5hFj26QkHmW4mKDt93K7yPqw3DJppJ48S2&si=4549899913920512&pi=a685a8d3-2f65-4b91-b132-5fa90a073360>
Garry Grant | CEO
***@***.******@***.***>
760.846.4233 Cell
760.444.9242 Direct

SEO Inc.
229 Croft Way
Mount Juliet, TN 37122
www.seoinc.com<https://t.sidekickopen08.com/s3t/c/5/f18dQhb0S7kv8cVX5FW29Hn-t59hl3kW7_k2842Pyh5PN1G6-wcvLTt7Vsgcjk2bzNJKf8C1-HG01?te=W3R5hFj26QkHmW4mKDt93K7yPqw3DJppJ48S2&si=4549899913920512&pi=a685a8d3-2f65-4b91-b132-5fa90a073360>
_____________________________________

**Comment by ceoseoinc** [comment]
Here is the exact error, how do I fix it


[Wed Aug 30 19:19:10.865586 2023] [php:error] [pid 21199] [client 69.130.145.17:0] PHP Fatal error:  Uncaught TypeError: MediaCloud\\Vendor\\Carbon\\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in /nas/content/live/seoinc/wp-content/plugins/ilab-media-tools-premium/lib/mcloud-nesbot/carbon/src/Carbon/Traits/Creator.php on line 97 and defined in /nas/content/live/seoinc/wp-content/plugins/ilab-media-tools-premium/lib/mcloud-nesbot/carbon/src/Carbon/Traits/Creator.php:927\nStack trace:\n#0 /nas/content/live/seoinc/wp-content/plugins/ilab-media-tools-premium/lib/mcloud-nesbot/carbon/src/Carbon/Traits/Creator.
php(97): MediaCloud\\Vendor\\Carbon\\Carbon::setLastErrors(false)\n#1 /nas/content/live/seoinc/wp-content/plugins/ilab-media-tools-premium/lib/mcloud-nesbot/carbon/src/Carbon/Traits/Creator.php(148): MediaCloud\\Vendor\\Carbon\\Carbon->__construct('2023-08-30 19:1...', Object(DateTimeZone))\n#2 /nas/content/live/seoinc/wp-content/plugins/ilab-media-tools-premium/classes/Tasks/Task.php(1037):
[Wed Aug 30 19:19:10.868244 2023] [php:notice] [pid 21199] [client 69.130.145.17:0] media-cloud.ERROR: [21199] Uncaught TypeError: MediaCloud\\Vendor\\Carbon\\Carbon::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in /nas/content/live/seoinc/wp-content/plugins/ilab-media-tools-premium/lib/mcloud-nesbot/carbon/src/Carbon/Traits/Creator.php on line 97 and defined in /nas/content/live/seoinc/wp-content/plugins/ilab-media-tools-premium/lib/mcloud-nesbot/carbon/src/Carbon/Traits/Creator.php:927 Stack trace: #0 /nas/content/live/seoinc/wp-content/plugins/ilab-media-tools-premium/lib/mcloud-nesbot/carbon/src/Carbon/Traits/Creator.
php(97): MediaCloud\\Vendor\\Carbon\\Carbon::setLastErrors(false) #1 /nas/content/live/seoinc/wp-content/plugins/ilab-media-tools-premium/lib/mcloud-nesbot/carbon/src/Carbon/Traits/Creator.php(148): MediaCloud\\Vendor\\Carbon\\Carbon->__construct('2023-08-30 19:1...', Object(DateTimeZone)) #2 /nas/content/live/seoinc/wp-content/plugins/ilab-media-tools-premium/classes/Tasks/Task.php(1037): MediaCloud\\Vendor\\Carbon\\Carbon::instance(Object(DateTime)) #3 [internal function]: MediaCloud\\Plugin\\Tasks\\Task->jsonSerialize() #4 /nas/content/live/seoinc/wp-includes/functions.php(4276): json_encode(Array, 0, 512) #5 /nas/content/live/seoinc/wp-includes/functions.
php(4439): wp_json_encode(Array, 0) #6 /nas/content/live/seoinc/wp-content/plugins/ilab-media-tools-premium/classes/Tasks/TaskManager.php(402): wp_send_json(Array) #7 /nas/content/live/seoinc/wp-includes/class-wp-hook.php(310): MediaCloud\\Plugin\\Tasks\\TaskManager->actionTaskStatus('') #8 /nas/content/live/seoinc/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array) #9 /nas/content/live/seoinc/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #10 /nas/content/live/seoinc/wp-admin/admin-ajax.php(188): do_action('wp_ajax_mcloud_...') #11 {main}   thrown {"file":"/nas/content/live/seoinc/wp-content/plugins/ilab-media-tools-premium/lib/mcloud-nesbot/carbon/src/Carbon/Traits/Creator.php","line":927} [], referer: https://www.seoinc.com/wp-admin/admin.


Best Regards,
***@***.***

[EO Inc.]<https://t.sidekickopen26.com/Ctc/GB+23284/cm3XX04/Jk82-6qcW5BW0B06lZ3lcW4_747b1dqL_hN58J54m7LGlxW7P1ltx6tz7l0W6TnmLL8Z5F-mVy0Cnm2T9-rbW673yN27Bzgd_W7YN4sQ2T-jSJW1bgxcs45nzJBVC3wBM80HHwhW6JZy5l6NsGD2W1vrKNT7_kDD9W1fWCSS3yP2zpW8Rx3zc1vvrlpW5tN-hJ7Dc9T9MRcKz4lFFtpW157bGX6c_4QkVpkpSH2GC9KHW5b2X5v2kQDtvf2YGC6n04>
Garry Grant | CEO
***@***.******@***.***>
760.846.4233 Cell
760.444.9242 Direct

SEO Inc.
229 Croft Way
Mount Juliet, TN 37122
www.seoinc.com<https://t.sidekickopen26.com/Ctc/GB+23284/cm3XX04/Jk82-6qcW5BW0B06lZ3lcW4_747b1dqL_hN58J54m7LGlxW7P1ltx6tz7l0W6TnmLL8Z5F-mVy0Cnm2T9-rbW673yN27Bzgd_W7YN4sQ2T-jSJW1bgxcs45nzJBVC3wBM80HHwhW6JZy5l6NsGD2W1vrKNT7_kDD9W1fWCSS3yP2zpW8Rx3zc1vvrlpW5tN-hJ7Dc9T9MRcKz4lFFtpW157bGX6c_4QkVpkpSH2GC9KHW5b2X5v2kQDtvf2YGC6n04>
_____________________________________

From: Garry Grant
Sent: Tuesday, August 29, 2023 10:13 AM
To: Interfacelab/ilab-media-tools ***@***.***>; Interfacelab/ilab-media-tools ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [Interfacelab/ilab-media-tools] Issues after installing PHP 8.2 and MediaCloud (Issue #215)


Would this be advisable, from WPengine support. What direction would you suggest?

We would recommend making a fresh copy to STG or DEV to troubleshoot further. The production site shows some files not verifying against checksums for WordPress core. STG or DEV can be used to reinstall core files. After that, the plugin should be checked to determine if the issue still persists on PHP 8.2.

Warning: File doesn't verify against checksum: wp-cron.php
Warning: File doesn't verify against checksum: wp-settings.php
Warning: File doesn't verify against checksum: wp-trackback.php
Error: WordPress installation doesn't verify against checksums.


The cause of the issue isn't known at the moment. It definitely helps that you've been able to get everything working with Local and that Mediacloud has been able to confirm their plugin working on PHP 8.2. The best thing would be to rule out possible culprits by making a new copy to staging or dev. That way, this can be troubleshoot further without affecting the live site.

The WordPress core files can be safely reinstalled there. That's the first thing I would recommend because of how you explained the issue. WordPress core and the must-use plugins are the potential differences between WPE and Local. They're probably not the only ones, but that's a start. We can reinstall core files in support chat any time.



Best Regards,
***@***.***

[EO Inc.]<https://t.sidekickopen26.com/Ctc/GB+23284/cm3XX04/Jk82-6qcW5BW0B06lZ3lcW4_747b1dqL_hN58J54m7LGlxW7P1ltx6tz7l0W6TnmLL8Z5F-mVy0Cnm2T9-rbW673yN27Bzgd_W7YN4sQ2T-jSJW1bgxcs45nzJBVC3wBM80HHwhW6JZy5l6NsGD2W1vrKNT7_kDD9W1fWCSS3yP2zpW8Rx3zc1vvrlpW5tN-hJ7Dc9T9MRcKz4lFFtpW157bGX6c_4QkVpkpSH2GC9KHW5b2X5v2kQDtvf2YGC6n04>
Garry Grant | CEO
***@***.******@***.***>
760.846.4233 Cell
760.444.9242 Direct

SEO Inc.
229 Croft Way
Mount Juliet, TN 37122
www.seoinc.com<https://t.sidekickopen26.com/Ctc/GB+23284/cm3XX04/Jk82-6qcW5BW0B06lZ3lcW4_747b1dqL_hN58J54m7LGlxW7P1ltx6tz7l0W6TnmLL8Z5F-mVy0Cnm2T9-rbW673yN27Bzgd_W7YN4sQ2T-jSJW1bgxcs45nzJBVC3wBM80HHwhW6JZy5l6NsGD2W1vrKNT7_kDD9W1fWCSS3yP2zpW8Rx3zc1vvrlpW5tN-hJ7Dc9T9MRcKz4lFFtpW157bGX6c_4QkVpkpSH2GC9KHW5b2X5v2kQDtvf2YGC6n04>
_____________________________________
