### ISSUE TITLE
Slow site load after plugin activation

### ISSUE THREAD

**Issue by LeTraceurSnork** [Interfacelab/ilab-media-tools#219]
I've activate this plugin (4.5.21 ver). After that all of my site pages started to load ~6.5 minutes (even WP-admin). Rollbacking to older versions (tried 4.5.0) didn't help. I know for sure that the issue is this plugin, since disabling it made the problem gone.

So, what may cause the problem?

p.s. Tried to watch some errors via `Query Monitor`, but it doesn't help since the page doesn't load

**Comment by jawngee** [comment]
What is this.  What is 'Slow s'?

**Comment by jawngee** [comment]
It's hard to say.  It could be you are hosting on some shit tier VPS stuff. 

Try going to WordPress admin -> Cloud Tasks -> Task Manager and click on settings.  Turn off 'enable media cloud heartbeat'.  That can cause a slow down if you have a lot of simultaneously active admins.

The only other way it could be slow is if your database is slow af.
