### ISSUE TITLE
Free version missing from plugin directory

### ISSUE THREAD

**Issue by Morpheus636** [Interfacelab/ilab-media-tools#230]
**Describe the bug**
The free version of Media Cloud is no longer listed in the WordPress Plugin Directory.

**To Reproduce**
1. Go to https://wordpress.org/plugins/ilab-media-tools/
2. See the error: 
   > This plugin has been closed as of March 7, 2024 and is not available for download. This closure is temporary, pending a full review.

**Expected behavior**
Plugin should be available for download 

**Screenshots**

**Server (please complete the following information)**
N/A

**How did you install the plugin?**
Wordpress.org

**Comment by jawngee** [comment]
We sent an update yesterday waiting for them to review.  See the latest release here to download it without waiting for wp.org to review it.

**Comment by Morpheus636** [comment]
Makes sense, just wanted to make sure this info was searchable. Thanks for the info!
