### ISSUE TITLE
Error when uploading product from woocommerce rest api

### ISSUE THREAD

**Issue by thienphu** [Interfacelab/ilab-media-tools#29]
Hi, just include  wp-admin/includes/image.php in iblab-media-tools.php

include_once (ABSPATH . 'wp-admin/includes/image.php');

**Comment by jawngee** [comment]
What's the error?

**Comment by jawngee** [comment]
86eff4e5957039a0079e8f433561d20ddffc8598 fixes some issues with WooCommerce so maybe it'll fix the issue you are having.

**Comment by jawngee** [comment]
I'm going to close this, but feel free to re-open it if you have more information about what the error is.
