### ISSUE TITLE
Bug related to delete files action with s3 bucket prefix and versioning feature

### ISSUE THREAD

**Issue by Lotykun** [Interfacelab/ilab-media-tools#3]
I have been testing the new update and it works as expected.. Now i can set a prefix according to my path in my s3 bucket. But there is a problem, in wp-offload s3 plugin.. there is an option in which you can upload your images with a versioning control, this means that in every file you upload, it is created a new folder with a timestamp which represents the version.. This is made because is normal to have your s3 bucket configure with an aws cloud-front, by the way, the versioning option helps to the invalidations produced in the cloud-front and ensure that the file your are looking for, is in the last version.

On the other hand the last develop about the prefix has broken the delete action.. When I set a new prefix, upload a new file, and afterwards i delete from the wordpress (with the option deletes in s3 too, activated), the file is not found, and consequentely is not erased.

I have develop my own solution for those issues. And I would like to get feedback about mi code and if you like it, be incorporated in the master branch for future updates. Sorry i do not know the correct flow for how i can recomend a new commit on github.. I am new on git. Because of that id prefer to send you the files i have modified. It is only one and is only a few lines of code. You can check where are the changes, but summing up it is only on line 390 and lines 292, 293.

All the design is located in the file ilab-media-tools/classes/tools/s3/ilab-media-s3-tool.php. And only takes a few code lines.

For the delete action bug.. I have modified line 390 “$this->delete_file($s3,$data[‘file’]);” for “$this->delete_file($s3,$data[‘s3’][‘key’]);” and now whatever prefix I have set.. the delete action is able to find it and erase from the bucket too

For the versioning bug. I have added the function get_object_version_string() from the plugin wp-offload s3, adpating the format to my requeriments, and i have also added new two options to the prefix in lines 292 and 293

$prefix = str_replace(“@{versioning}”, $this->get_object_version_string(), $prefix);
$prefix = str_replace(“@{site-id}”,sanitize_title(strtolower(get_current_blog_id())), $prefix);

These two options “@{versioning} and @{site-id}” allows me to implement the same path that i had in the bucket.. Using the “multisite” folder, and the “versioning feature”. The prefix set in the AWS BUcket Prefix setting will be "wp-content/uploads/sites/@{site-id}/@{date:Y/m}/@{versioning}"
[ilab-media-s3-tool.php.zip]

(https://github.com/Interfacelab/ilab-media-tools/files/776438/ilab-media-s3-tool.php.zip)

**Comment by jawngee** [comment]
Thanks for this!

Committed 6c837fc5dd377184349212e7bdd48230a85b3a27
