### ISSUE TITLE
Support of ILAB_AWS_S3_SESSION_TOKEN for EC2 with Instance profile and IAM role

### ISSUE THREAD

**Issue by abdennour** [Interfacelab/ilab-media-tools#36]
When we assigned IAM role to an EC2 instance, the credentials to access the S3 will not only `ILAB_AWS_S3_ACCESS_KEY` and `ILAB_AWS_S3_ACCESS_SECRET` but also a token.

Those 3 settings are automatically available in the EC2 instance attached to an instance profile with IAM role.

```sh
ENDPOINT=http://169.254.169.254/latest/meta-data/iam/security-credentials/;
KEYS=$(curl -s $ENDPOINT`curl -s $ENDPOINT`);

# Fill in ILAB env vars
ILAB_AWS_S3_ACCESS_KEY=$(echo $KEYS | jq ".AccessKeyId");
ILAB_AWS_S3_ACCESS_SECRET=$(echo $KEYS | jq ".SecretAccessKey");
#⚠️⚠️⚠️ the one below is missing ⚠️⚠️⚠️⚠️
ILAB_AWS_S3_SESSION_TOKEN=$(echo $KEYS | jq ".Token"); # << WE REQUEST the support of this one
```

**Comment by drAlberT** [comment]
it should use the php SDK credential helper instead ..  your method will not renew the credentials (which by default expire in 1 hour)

**Comment by jawngee** [comment]
#31 was merged.

Though after you upgrade to 3.x note that the environment variables `ILAB_AWS_S3_USE_CREDENTIAL_PROVIDER` and `ILAB_CLOUD_USE_CREDENTIAL_PROVIDER` are ***deprecated*** and you will need to use `MCLOUD_STORAGE_S3_USE_CREDENTIAL_PROVIDER`
