### ISSUE TITLE
`Undefined index: s3` prevents upload

### ISSUE THREAD

**Issue by JulienMelissas** [Interfacelab/ilab-media-tools#4]
Looks like I'm getting this on every cropping size, as well as for the full-res image. So on default WP I get this error 4x. Pretty sure I've entered everything in correctly. Screenshot of S3 settings:
![aws-settings](https://cloud.githubusercontent.com/assets/2278221/23015816/3d8bf83c-f402-11e6-8c34-806be30b9325.png)

Here's the error:
`Notice: Undefined index: s3 in /srv/www/cellar.example.com/current/web/app/plugins/ilab-media-tools/classes/tools/s3/ilab-media-s3-tool.php on line 185`

For fun, I tried removing the code in the if statement and just used the code on [line 187](https://github.com/Interfacelab/ilab-media-tools/blob/master/classes/tools/s3/ilab-media-s3-tool.php#L187) and it didn't throw the errors, but it doesn't look like it's uploading to S3 as my bucket is empty.

I tried turning Imgix off and the issue's still there.

Running a [Trellis](https://roots.io/trellis/) box with an up-to-date Bedrock install on multisite. Your plugin is install as a normal plugin with composer and is network activated.

Any thoughts? Thanks so much! Super excited to use this.

**Comment by JulienMelissas** [comment]
I should mention - it looks like the importer isn't working either.

**Comment by jawngee** [comment]
Do you have error_log setup in php.ini?  If not, you should turn it on.  If an S3 upload fails, the log file will be spammed with the reason.

Importer won't work until S3 works ;)

**Comment by JulienMelissas** [comment]
Thanks for the reply. I just re - set everything up when it comes to the buckets and users because they had been created a while ago. I didn't have the proper permissions set on my AWS user. Stupid me. facepalm. Thanks SO much - this thing rules.
