### ISSUE TITLE
Remove Backblaze Support

### ISSUE THREAD

**Issue by jawngee** [Interfacelab/ilab-media-tools#43]

**Comment by damashe** [comment]
Hey, sorry if I am doing this wrong…
Just curious why remove Backblaze b2?

**Comment by jawngee** [comment]
Backblaze support will be put into an unsupported "add-on" plugin, it just won't be in core though.

Dealing with B2 support questions and confusion, it's just not worth supporting from my perspective.  I don't use it, my clients don't use it.  I personally don't feel like it's a great fit for the purpose, the API kinda sucks, it's much slower than other alternatives and while it might be cost effective, it's *not* that much more cost effective.

If it's in its own add-on plugin, maybe Backblaze can take on that project and support it themselves.

Or, if someone wants to come forward and maintain it in the core and take that on as their thing, then that's fine too.

**Comment by damashe** [comment]
Makes sense to me…  
I've been trying B2 out on a few small sites, once I found media tools, as an alternative to S3. It seemed like a good idea for very low traffic, budget constrained sites.  
The transaction time according to NewRelic APM did seem high to me, but I am so new to developing that it could have been my errors.  
Thanks for the clarifications though.
