### ISSUE TITLE
plugin in new WordPress block layout (WP 5.0)

### ISSUE THREAD

**Issue by jsutphin1** [Interfacelab/ilab-media-tools#54]
Wordpress' new block layout with responsive images adds a bad source path for images uploaded to the AWS cloud resulting in images not showing. If I disable the plugin, all images show. the source set for responsive images are all pointed to the correct AWS bucket, but the original source file path is not.  In our wp install, the source image points to the image in the wp database with the addition of a "/h" at the end of the source URL. Thank you for any assistance on this issue.

**Comment by Phalconline** [comment]
I have the same problem

**Comment by Phalconline** [comment]
@jsutphin1 Hey, if you enable ImagIX it will fix a bug. It Tmp solutions while S3 doesn't work correctly with a plugin.

**Comment by famedpirate** [comment]
Any solutions to the issue?

@Phalconline - Do you mean to enable Imgix temporarily until a fix?

**Comment by jawngee** [comment]
Fixed in 3255d46b0906df74998f334af8128288fdcc987b

**Comment by jawngee** [comment]
Actually, was fixed in 78e4d759f56961ee82cf6a24dd52304de579e573

**Comment by jsutphin1** [comment]
Thanks jawngee, the update fixed my issues and now working exactly as before
