### ISSUE TITLE
Unlink cloud media from the cloud? 

### ISSUE THREAD

**Issue by rickygu** [Interfacelab/ilab-media-tools#56]
I imported about 200 images to the wrong cloud directory, then I deleted the files on the cloud, now all 200 of my media are pointing to empty cloud locations. I tried reinstalling but the data isn't purging. I can't delete the 200 images and start over as they link to many different posts. 

Maybe each image should have a "unlink" option to unlink from the cloud? meanwhile how do I clear this manually?

**Comment by rickygu** [comment]
Ok I managed to delete _wp_attachment_metadata from the database.

**Comment by jawngee** [comment]
In the metadata for each attachment is a key called S3.  That has to be unset.  I would do something like:

```php
    $q = new \WP_Query([
        'post_type' => 'attachment',
        'post_status' => 'inherit',
        'posts_per_page' => -1
    ]);

    foreach($q->posts as $post) {
        $meta = wp_get_attachment_metadata($post->ID);
        if (isset($meta['s3'])) {
            unset($meta['s3']);
            wp_update_attachment_metadata($post->ID, $meta);
        }
    }
```

Make sure Storage Tool (or the plugin) is disabled first.

Don't delete _wp_attachment_metadata because it contains a lot of file info that you need.

**Comment by rickygu** [comment]
ops damn looks like i'll have to restore the database from backup.
