### ISSUE TITLE
Error executing "ListBuckets"

### ISSUE THREAD

**Issue by mushbrain666** [Interfacelab/ilab-media-tools#59]
Attempting to set up IMGIX and S3. IMGIX subdomain is deployed using an IAM user belonging to a group made with [Sample Policies for Wordpress](http://stretcheverydev/wp-admin/admin.php?page=media-tools-support). 

Can't get past this error in Troubleshooter:

> Validate Storage Settings
> There was an error or errors trying to connect to the storage provider.
> 
> Error insuring that stretcheveryday exists. Message: Error executing "ListBuckets" on "https://s3.ca-central-1.amazonaws.com/"; AWS HTTP error: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

This is the libcurl error:

```
CURLE_PEER_FAILED_VERIFICATION (60)

The remote server's SSL certificate or SSH md5 fingerprint was deemed not OK. This error code has been unified with CURLE_SSL_CACERT since 7.62.0. Its previous value was 51. 
```

This is my policy:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "s3:DeleteObjectTagging",
        "s3:ListBucketMultipartUploads",
        "s3:DeleteObjectVersion",
        "s3:ListBucket",
        "s3:DeleteObjectVersionTagging",
        "s3:GetBucketAcl",
        "s3:ListMultipartUploadParts",
        "s3:PutObject",
        "s3:GetObjectAcl",
        "s3:GetObject",
        "s3:AbortMultipartUpload",
        "s3:DeleteObject",
        "s3:GetBucketLocation",
        "s3:PutObjectAcl"
      ],
      "Resource": [
        "arn:aws:s3:::stretcheveryday/*",
        "arn:aws:s3:::stretcheveryday"
      ]
    },
    {
      "Effect": "Allow",
      "Action": "s3:HeadBucket",
      "Resource": "*"
    }
  ]
}
```

Trying to connect from a local installation, does that matter? 

Do I need to do something with Public Access Settings or Access Control List in the Bucket? I added the CORS snippet:

```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>HEAD</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

Any suggestions greatly appreciated. [Debug Log](https://gist.github.com/mushbrain666/b7164dfd3af3d0100d82800f816e727a)

**Comment by jawngee** [comment]
In the bucket permissions in the S3 console, make sure the following are unchecked:

- Block new public ACLs and uploading public objects
- Remove public acess granted through public ACLs
- Block public and cross-account access if bucket has public policies
- Block new public bucket policies

It should look like this:

![screenshot of safari 1-29-19 4-14-20 pm](https://user-images.githubusercontent.com/44449/51897259-f1547000-23e0-11e9-9588-572132f64831.png)

**Comment by mushbrain666** [comment]
Thank you!  

When I selected the bucket from the S3 bucket archive and hit 'edit public access settings' the boxes were unchecked, however when I went into the bucket itself > permissions > public access settings they were checked.  Strange considering I actually had to select the bucket on the archive page to see the unchecked settings, didn't seem like a setting 'for all buckets'. This is what I saw on the bucket archive page:

![s3-settings](https://user-images.githubusercontent.com/45631311/51908362-449dd280-238f-11e9-83dd-670fec2ef471.JPG)

Confusing, however unchecking the boxes from the deeper dialog solved my 403. 

Now I have a warning with a small typo (*this may not **be** matter) 

![troubleshooter](https://user-images.githubusercontent.com/45631311/51910716-a4977780-2395-11e9-8a84-ddb2d284ecd9.JPG)

I see the [s3 file](https://stretcheveryday.s3.ca-central-1.amazonaws.com/_troubleshooter/sample.txt) is hidden, while the [imgix file](http://stretcheveryday.imgix.net/_troubleshooter/sample.jpg?ixlib=php-1.2.1) is visible - is this expected behavior? Also I see no sample .txt file, I guess it gets deleted right away?

On localhost the Troubleshooter gets as far as testing the IMGIX image, but on dev server its an endless spinning wheel after testing bulk importer. 

The storage importer appears to work, through admin on both local and dev I see the cool animation of images going into the cloud, but upon completion nothing happens. If I use WP-CLI it is lightning fast, the images all appear to load, but I see nothing in my bucket or on IMGIX. 

I tried upload a few times and noticed locally a failure in between false-positives:

![weird](https://user-images.githubusercontent.com/45631311/51911651-022cc380-2398-11e9-80dd-fb4eb371e939.JPG)

So I see the image of what I assume is your cute kid on S3 and being served by IMGIX, so thats cool, but I'm stumped on where to go from here. Thanks for any advice.

**Comment by mushbrain666** [comment]
So the bucket policies are a bit complicated: [S3 Blog](https://aws.amazon.com/blogs/aws/amazon-s3-block-public-access-another-layer-of-protection-for-your-accounts-and-buckets/). 

Changing bucket and object permissions post-creation was murky, so I created a new bucket. Same name, same CORS config, with public settings enabled on creation. 

I can access the image from the [S3 server](https://s3.ca-central-1.amazonaws.com/stretcheveryday/56u.jpg) and [IMGIX subdomain](http://stretcheveryday.imgix.net/56u.jpg), so things are clearly working between S3 and IMGIX.

Now the troubleshooter passes locally:
![test-pass](https://user-images.githubusercontent.com/45631311/51983833-53ec5100-245f-11e9-81c5-80b52b1a1a02.JPG)

But hangs on live dev - whether or not background processing is enabled, and the image is clearly on IMGIX so not sure what to make of it:
![test-fail](https://user-images.githubusercontent.com/45631311/51983895-86964980-245f-11e9-9ab1-62e150a97c20.jpg)

I also don't understand the Privacy ACL settings. "Leave it as public-read unless you are using imgix" infers it should be authenticed:
![privacy-acl](https://user-images.githubusercontent.com/45631311/51984321-a712d380-2460-11e9-80d6-9f1313a18518.JPG)

However unless its public the troubleshooter doesn't pass:
![privacy-acl-error](https://user-images.githubusercontent.com/45631311/51984336-b265ff00-2460-11e9-8400-9f1c06116421.JPG)

The importer runs through wp-admin and through CLI with no errors, or dialog at all when it finishes. 

At this point I am pretty much burnt. Can anybody confirm that they actually have currently working Media Cloud setup? I am happy to pay for a solution and can provide access to live dev.

**Comment by jawngee** [comment]
You should set it to `public-read` unless you are using Imgix.  The troubleshooter error is a bit of a red herring as it doesn't check if you've specified public or private default ACL for uploads, it just tries to read the file regardless and shows the error if it can't.

This plugin is in use on over 3000+ websites.  Every client website my company builds uses it (for clients like Nike, AT&T, etc.).

I just posted a guide on configuring S3 here:  https://discourse.interfacelab.io/t/amazon-s3-setup/123

**Comment by jawngee** [comment]
Drop me an email at jon@interfacelab.com

**Comment by mushbrain666** [comment]
Great guide hadn't seen that, but yes I did all the steps. Went through and double checked.

Thanks for the encouragement. Emailed you.

**Comment by mushbrain666** [comment]
Still haven't got full upload working but at this point this thread is a mess. I did solve my initial issue though and things are *sort* or working so closing this issue.
