### ISSUE TITLE
"Auto compress" checkbox like the "Auto format" checkbox for Imgix

### ISSUE THREAD

**Issue by JulienMelissas** [Interfacelab/ilab-media-tools#6]
Loving this plugin. I'm trying to further optimize image delivery via Imgix and came across this article: https://blog.imgix.com/2016/11/30/passing-pagespeed.html, which suggests that `auto=compress` is used - would you be open to a PR which adds this checkbox to the backend? The `q=` parameter would be respected as well 👍 - if so, I'll go ahead and submit a PR. Thanks!

**Comment by JulienMelissas** [comment]
I also just did a little bit of digging and it looks like you're [using](https://github.com/Interfacelab/ilab-media-tools/blob/master/classes/tools/imgix/ilab-media-imgix-tool.php#L397-L407) the `fm=` formatting param. I'd suggest a change to using the `auto` param and then specifying `format` in it instead. Let me know if you're open to that PR as well. Thanks!

**Comment by JulienMelissas** [comment]
This is now done in https://github.com/Interfacelab/ilab-media-tools/pull/7. Please test and let me know what you think!

**Comment by jawngee** [comment]
Looks great, merged.
