### ISSUE TITLE
Missing region in AWS S3: Paris (EU)

### ISSUE THREAD

**Issue by tristanbes** [Interfacelab/ilab-media-tools#62]
Hello,

I've got buckets on regions EU - Paris which is key `eu-west-3` 
Yet this plugin does not offer the ability to choose this region.

Can you add it please ?

**Comment by jawngee** [comment]
What happens if you set it to auto-detect and then hit save?

(Extra regions have been added to 3.0, but I'm just curious).

**Comment by tristanbes** [comment]
So i've added : 
`ILAB_AWS_S3_REGION='eu-west-3'` in my .env file. with no effect.

I've added in `application.php` (i use bedrock edition)
`Config::define('ILAB_AWS_S3_REGION', 'eu-west-3');` 
with no effect, it still says "Your AWS S3 settings are incorrect or the bucket does not exist. Please verify your settings and update them."

**Comment by tristanbes** [comment]
oh, so if I use your direct github repository with dev-master, the region should appear then ?

**Comment by jawngee** [comment]
No, 3.0 dev is happening in a totally separate private repo.

**Comment by jawngee** [comment]
I can push a change to this repo that will enable the extra regions though.  Will do tonight.  You'll have to use this repo instead of using the plugin from the wordpress repository though.

**Comment by tristanbes** [comment]
:(((((((((

**Comment by tristanbes** [comment]
yeah, no problem using your repo directly since we use bedrock edition and require all our plugins via composer ;-)

**Comment by jawngee** [comment]
Added in this release:

https://github.com/Interfacelab/ilab-media-tools/releases/tag/2.1.31

Should be able to just composer update.
