### ISSUE TITLE
mediacloud import not honoring "Upload File Prefix"

### ISSUE THREAD

**Issue by eb112** [Interfacelab/ilab-media-tools#63]
When issuing the `wp mediacloud import` command, all files are imported into the base directory of our object storage bucket using the default WordPress prefix.

Note that newly-uploaded images do honor this setting. Only when running the script from the command line is there a problem.

**Comment by craigpearson** [comment]
Seconded, this setting isn't honored when using the import tool either in the GUI or via WP CLI. It honored when manually uploading media though

A shame as this means the plugin is not compatible with multisite installs. I've investigated adding this functionality but doesn't seem to be a small task to do so

**Comment by JEricaM** [comment]
I have the same problem, I can't use the plugin if this problem persist.

**Comment by jawngee** [comment]
The plugin preserves your existing file paths on import because a lot of people complained that it didn't on the support forums.  I can add a switch for the CLI but the web UI is a different beast.

Either way it won't happen for awhile as we are gearing up to release 3.0 in the next few weeks.

**Comment by JEricaM** [comment]
I think that the switch for the CLI will be a good solution.

**Comment by arwinjp** [comment]
I'm facing same issue. Could you please point me which class I need to modify to make this work for me?

**Comment by alexraileanu** [comment]
as a temporary solution until we have a check on the CLI or something, i found that setting the `$preserveFilePath` parameter in `classes/Tools/Storage/StorageTool.php:1804` where `updateAttachmentMetadata` is called to `false` solves the issue. 

note that this only works for importing via the CLI.
