### ISSUE TITLE
TYPO for filter "ilab_imgix_filter_parameters"

### ISSUE THREAD

**Issue by patrickbjohnson** [Interfacelab/ilab-media-tools#64]
In the documentation there is a reference to this filter: `ilab_imgix_filter_parameters`

And while attempting to use I realize it wasn't working...at all. Took a look at the code and noticed there is a typo in how the filter is referenced. 

Within the documents, the filter is referenced with underscores (`_`) and in the code, the filter is referenced with hyphens (`-`). 

Code:`apply_filters('ilab-imgix-filter-parameters', $params, $size, $id, $meta);`
Documentation: `apply_filters('ilab_imgix_filter_parameters', $params, $size, $id, $meta);`

Can be found here: https://github.com/Interfacelab/ilab-media-tools/blob/54002798d41d65c5b3ce292e8cdeb305f60711d9/classes/Tools/Imgix/ImgixTool.php#L401

**Comment by patrickbjohnson** [comment]
Mostly concerned if this will ever change as the documentation and the actual code are not aligned. And updating the code could cause breaking changes to any users.

**Comment by jimmitjoo** [comment]
You saved my day, thank you!
