### ISSUE TITLE
using S3 & media cloud - images and thumbnail won't load

### ISSUE THREAD

**Issue by starwarsinfinity** [Interfacelab/ilab-media-tools#66]
Hi, 
I've setup WP with S3 and media cloud. I ran the troubleshooting to verify all setting are good and they are but I go to the media library and the image has a cloud  icon on it.  I select the image to be used on a page and it doesn't show up.

Is there something not enabled?

PHP VERSION COMPATIBILITY
Your version of PHP (7.1.26) is compatible.

VALIDATE STORAGE SETTINGS
Was able to successfully connect to storage provider.

UPLOAD SAMPLE FILE
Was able to successfully upload a sample file.

VERIFY UPLOADED FILE IS PUBLICLY ACCESSIBLE
The uploaded file is publicly accessible.

DELETE UPLOADED FILE
The uploaded file was successfully deleted.

**Comment by jawngee** [comment]
What do you mean it doesn't show up?  The `img` tag has an empty `src` attribute or the `img` tag is missing completely?

**Comment by starwarsinfinity** [comment]
It's happening just like this section. I am also using the AWS Cloudfront for CDN. 
on this thread they recommended looking at the HTTP>HTTPS which I have properly defined the URL with HTTPS.
https://discourse.interfacelab.io/t/image-not-load-from-cdn-when-enable/68

**Comment by starwarsinfinity** [comment]
the new uploaded images will not show on any page that I try to use them. All I see in the media library is the cloud icons just like I reference on the link above.

**Comment by starwarsinfinity** [comment]
ok, just digging deeper at the page's source code I found this error message:
Failed to load resource: the server responded with a status of 404 (Not Found)

when I open the image and look at the storage URL vs Public URL, the public url doesn't load the image, the storage URL does. 

This XXXXXXXXX.com page can’t be found No webpage was found for the web address: https://XXXXXXXXXXXXXXXX.com/f2019Fri,%2001%20Mar%202019%2002:37:31%20+000003am31/cta-bg-reporting.jpg
HTTP ERROR 404

**Comment by starwarsinfinity** [comment]
is this a partial fix as to why the Public URL is pointing to the website+image path instead of the storage URL (CDN)?
https://discourse.interfacelab.io/t/how-to-make-images-load-from-cloud-storage-edited/54/9

**Comment by starwarsinfinity** [comment]
Does anyone have any recommendations?

**Comment by robcifre** [comment]
What was the answer to this? I'm not getting any images loading in the library either. I'm not even getting thumbnails with question marks on it.

**Comment by jawngee** [comment]
If you're getting 404 errors, your cloud storage settings are wrong.  The most common we see is that people have setup their amazon bucket with "Block Public Access" enabled, which you don't want to do.

@robcifre Can you be more vague?  :)  What provider are you using, which version of the plugin, which PHP version, wordpress version, etc, etc

If you paid for the premium verison you should open a ticket at https://support.mediacloud.press/submit-issue/
