### ISSUE TITLE
Image path not being served from remote storage (points to local uploads/)

### ISSUE THREAD

**Issue by tristanbes** [Interfacelab/ilab-media-tools#73]
Hello,

We were using S3 Uploads plugin so far with a S3-compliant service (Scaleway). I wanted to personnally try your plugin which does more thing out of the box.

We're using a Bedrock structure with PHP 7.3

Here's what I put for the `.env` values: 

```bash
ILAB_CLOUD_STORAGE_PROVIDER=other-s3
ILAB_MEDIA_S3_ENABLED=true
ILAB_MEDIA_CROP_ENABLED=true
ILAB_AWS_S3_ACCESS_KEY=xxxxxxxxx
ILAB_AWS_S3_ACCESS_SECRET=xxxxxxxxxxxxxxx
ILAB_AWS_S3_BUCKET=wp-sps-loisirs
ILAB_AWS_S3_ENDPOINT=https://s3.fr-par.scw.cloud
```

The troubleshooting gives me no errors
```
PHP VERSION COMPATIBILITY
Your version of PHP (7.3.3-1) is compatible.

VALIDATE STORAGE SETTINGS
Was able to successfully connect to storage provider.

UPLOAD SAMPLE FILE
Was able to successfully upload a sample file.

VERIFY UPLOADED FILE IS PUBLICLY ACCESSIBLE
The uploaded file is publicly accessible.

DELETE UPLOADED FILE
The uploaded file was successfully deleted.

TEST BULK IMPORTER
Your WordPress server configuration supports background processing.
```

Yet, the images both in the backoffice and on the front office are loaded from 
`http://tiger-jump.wordpress.vm/app/uploads/2016/11/Mise-en-ligne-du-site.jpg`

Instead of: 
`https://wp-sps-loisirs.s3.fr-par.scw.cloud/uploads/2016/11/Mise-en-ligne-du-site.jpg`

I tried to check/uncheck *Path Style Endpoint* but with no success.

What am I missing please ?

PS: Also, the settings view from the plugin inside wordpress backoffice is not reporting the values when they are provided through a `.env` file which is confusing because it led me that the plugin didn't read the env values

**Comment by jawngee** [comment]
If those are existing images on your server, Media Cloud doesn’t touch them unless you run them through the import process.

Any new uploads since enabled Media Cloud should serve from the .cloud domain.

If that’s not the case, please email me jon@interfacelab.com

-- 

jon gilkison
principal, interfacelab
https://linkedin.com/in/jongilkison <https://linkedin.com/in/jongilkison>
https://github.com/jawngee <https://linkedin.com/in/jongilkison>
http://interfacelab.io/ <http://interfacelab.io/>

**Comment by tristanbes** [comment]
We were already using the remote storage with the other plugin, so all our assets are already stored on our S3 storage.

Do you mean that it doens't just "rewrite" url's so I have to find a solution for any existing medias already on the cloud (but no longer on the local filesystem ?)

Thanks for your quick reply !

**Comment by jawngee** [comment]
Yes.

Media Cloud only rewrites URLs it has metadata for, metadata that it generates during an upload.  

Conceivably you could write a script to generate that metadata for you.  I will follow up with a more detailed note in the morning (it’s 11pm here).

Thanks,

Jon.


-- 

jon gilkison
principal, interfacelab
https://linkedin.com/in/jongilkison <https://linkedin.com/in/jongilkison>
https://github.com/jawngee <https://linkedin.com/in/jongilkison>
http://interfacelab.io/ <http://interfacelab.io/>

**Comment by tristanbes** [comment]
If you have a similar script or detailled directions on how to do so, i'm more than willing to take it because i'm not a WordPress developper
