### ISSUE TITLE
Message "To start using Imgix, you will need to set it up." never disappears

### ISSUE THREAD

**Issue by tristanbes** [Interfacelab/ilab-media-tools#75]
Hello,

It seems the notice "To start using Imgix, you will need to set it up." is never hiding.

We're not interested in using Imgix and I didn't enable the Imgix support nor in the UI, neither in the .env file.

 
![Media_Cloud_Tools_‹_Tiger_Jump_—_WordPress](https://user-images.githubusercontent.com/346010/56912165-ffcd2900-6aae-11e9-80d3-101c29e43918.png)

**Comment by jawngee** [comment]
Yeah, that's gone in 3.0
