### ISSUE TITLE
v3 roadmap status 

### ISSUE THREAD

**Issue by tristanbes** [Interfacelab/ilab-media-tools#80]
Hello,

Can we get an update on version 3 please ?
https://discourse.interfacelab.io/t/media-cloud-3-0-roadmap/51

I remember you mentionning the availability during past april.

**Comment by jawngee** [comment]
We are launching it June 26th.  I've been swamped in client work, kids, etc.

https://mediacloud.press/
https://talk.mediacloud.press/

**Comment by jawngee** [comment]
Sorry June 24th

**Comment by tristanbes** [comment]
any news :D

**Comment by jawngee** [comment]
Beta is available, email me jon@interfacelab.com
