### ISSUE TITLE
Is this plugin still being developed/supported?

### ISSUE THREAD

**Issue by dciphered** [Interfacelab/ilab-media-tools#81]
No one has been replying to any of the recent support threads for this plugin and I'm sure we'd all like to know if this plugin is still being developed and supported?

Real shame if it's not.

**Comment by jawngee** [comment]
Yes, 3.0 is dropping on June 26th.

https://mediacloud.press/

**Comment by dciphered** [comment]
Marvellous!

Do you have a prospective change log available, I can’t see to fine anything on the feature list via the supplied forum link.

**Comment by jawngee** [comment]
This is the full feature list:

Cloud Storage
--
- Amazon S3
- DigitalOcean Spaces
- Google Cloud Storage
- Wasabi
- Minio
- Backblaze
- Other S3 compatible services
- Transfer acceleration
- Pre-signed URLs
- Ability to set caching info
- Custom upload directories
- Custom CDN
- Custom document CDN
- Storage browser for browsing cloud storage directly in WordPress
- Media list integration
- Upload directly to the cloud, bypassing WordPress
- Import media from cloud storage
- Migrate local media to cloud storage
- Rebuild thumbnails

Dynamic Image Generation
--
Dynamic image generation is now built-in to the plugin providing Imgix-like features without requiring Imgix.  Imgix will always be the better option, but it can be overkill for smaller sites.

- Advance image editor
- Built-in dynamic image generation
- Real-time dynamic image transforms
- Watermarking images

General
--
- Network level multisite support
- Image size manager
- Advanced image crop tool
- Revamped UI

Imgix
--
- Imgix support
- Advance image editor
- Render PDF files
- Detect faces
- Resize animated GIFs (Imgix Premium Account)
- Convert animated GIFs to MP4 (Imgix Premium Account)
- Advanced image optimization
- Global image CDN
- Real-time dynamic image transforms
- Watermarking images

Integrations
--
- WPML
- WooCommerce
- Easy Digital Downloads
- WP Job Manager
- EWWW Image Optimizer
- Smush Image Optimizer
- ShortPixel Image Optimizer
- Imagify Image Optimizer

Vision
--
- Detect faces
- Face Recognition in the browser (no external service needed)
- Amazon Rekognition
- Google Cloud Vision
- Automatic tagging with machine learning
- Automatic classification with machine learning
- Automatic moderations with machine learning

Assets
--
Your site assets can now be pushed or pulled to a CDN with easy versioning support.

- Store javascript and CSS assets in the cloud
- Push mode (assets are pushed to the cloud)
- Pull mode (assets are pulled from WordPress by CDN)
- Custom asset versioning
- Control caching and content expiration
