### ISSUE TITLE
Media cloud not working with imagify

### ISSUE THREAD

**Issue by jasonbiondo** [Interfacelab/ilab-media-tools#82]
After I upload a file and imagify compresses it, the file is not being uploaded to my google cloud storage.

**Comment by jawngee** [comment]
Yeah, imagify has changed the hooks we were using in their latest release.

This will be fixed in 3.0 hopefully.  If you are paying $10 for imagify, you might as well just use Imgix, imho.  You then get the benefit of direct uploads to S3, skipping WordPress completely.

**Comment by jawngee** [comment]
And of course they don't document anything.

**Comment by jasonbiondo** [comment]
@jawngee I switched over to imgix but I'm having other issues now.  

For some reason cropping is required with imgix?  

Because of this my logos are cut off on certain pages.  Any suggestions on how to handle this?

![image](https://user-images.githubusercontent.com/1186147/59872486-d9699280-9367-11e9-8673-d8d3c0d97f3b.png)

**Comment by jawngee** [comment]
The crop tool is required with Imgix because once Imgix is enabled WordPress no longer generates pre-cut/pre-sized thumbnails or sizes, it relies on Imgix to do that.

If you are seeing cropping like that it's because the image size that you have defined in your theme has crop set to true.

But I just looked at the URL and everything looks kosher.  If you are seeing cropping that is not expected, if you look at the imgix image URL in the HTML it'll tell you if is cropping or resizing by the fit parameter.

**Comment by jasonbiondo** [comment]
@jawngee We are using thrive architect to build our pages and an example of the image url is: https://trekeffect-pages.imgix.net/2018/12/airbnb.png?auto=compress%2Cformat&fit=crop&h=150&ixlib=php-1.2.1&w=150&wpsize=thumbnail%20150w 

which doesn't look good at all.  

This is the original source: 
![image](https://user-images.githubusercontent.com/1186147/59873073-3b76c780-9369-11e9-85fc-f6a16869c26c.png)

When fit=crop is removed from the url it displays correctly: https://trekeffect-pages.imgix.net/2018/12/airbnb.png?auto=compress%2Cformat&h=150&ixlib=php-1.2.1&w=150&wpsize=thumbnail%20150w

**Comment by jawngee** [comment]
So if you look at the URL for an imgix image, you'll see a parameter called `wpsize`.  This tells you which pre-defined WordPress size is being used to figure out the width/height/cropping.  You have cropping turned on for the default 'thumbnail' size, which you can turn off in *Settings > Media* in the WordPress admin.

You should also turn on signing for Imgix once you get it working how you like.

**Comment by jasonbiondo** [comment]
@jawngee I have unchecked this box but images are still coming in at the wrong size.  What can I do?

![image](https://user-images.githubusercontent.com/1186147/59886023-64a84f80-938b-11e9-8d13-90fa035ee669.png)

**Comment by jawngee** [comment]
Did that work?

**Comment by jawngee** [comment]
So I tested this out in a generic install and it works as expected.  You can test it out too:

- Get an ID for an image by going into the Media section of admin, clicking on an image and copying the number from the URL, which should be something like: `https://mediacloud.test/wp/wp-admin/upload.php?item=15`.  We want that number following `item=`
- In one of your theme files like maybe `index.php`, add this line:  `<?php echo wp_get_attachment_image(15, 'thumbnail') ?>`, replacing 15 with the number you got in the previous step.  
- Now view that page in your browser and inspect the image.  If you have cropping turned off in your Media Settings, but it is still showing up as cropped than something else somewhere else is turning it on.

**Comment by jawngee** [comment]
One last thing you can do too is filter the imgix parameters in your theme's `functions.php` file:

```
add_filter('ilab-imgix-filter-parameters', function($params, $size, $id, $meta) {
	if ($size == 'thumbnail') {
		$params['fit'] = 'fit';
	}

	return $params;
}, 1000, 4);
```

**Comment by jawngee** [comment]
Note that in 3.0, being released next week, the filter is named `media-cloud/imgix/filter-parameters`, just FYI

**Comment by jasonbiondo** [comment]
@jawngee the easiest work around for me is to reupload the image.  Now that the crop setting has been changed this seems to be the easiest.
