### ISSUE TITLE
v3 Launch?

### ISSUE THREAD

**Issue by fghafoor85** [Interfacelab/ilab-media-tools#86]
I have an project on hold since I thought it's better to wait for 3. Big Project with over 60k media files that i need to migrate into s3.

Do you think you have a ETA or should I just go ahead and work with version 2 and upgrade later?

Thank you and very excited to see the v3!

**Comment by jawngee** [comment]
You can email me at jon@interfacelab.com and we will send you 3.0.  It's ready to drop, we are still working on marketing materials though.

**Comment by fghafoor85** [comment]
Just emailed thank you :)
