### ISSUE TITLE
mp3 (and metadata) support?

### ISSUE THREAD

**Issue by jtbayly** [Interfacelab/ilab-media-tools#87]
Hi there,

I just used this plugin to move a whole bunch of media files (images and MP3s) to Amazon S3 storage. I'm having some problems related to metadata in Wordpress. 

1. The file sizes are not known to Wordpress anymore (even for old images, but also MP3s.) 
Here are a couple of screenshots that show the missing file sizes. 
<img width="325" alt="Screen Shot 2019-07-16 at 4 52 32 PM" src="https://user-images.githubusercontent.com/210024/61331225-88767e00-a7ef-11e9-9c67-26d55ae814bd.png">
<img width="239" alt="Screen Shot 2019-07-16 at 4 53 45 PM" src="https://user-images.githubusercontent.com/210024/61331242-91674f80-a7ef-11e9-821a-e794b7a4cb0e.png">

2. Seriously Simple Podcasting (the plugin) can no longer figure out the length (Min:Sec) or the recorded date of the MP3s in cloud storage, but *does* figure out the file size. (This means the RSS feed for the podcast is missing crucial info—the length of each episode.)
Here's one of the old MP3s with some auto-filled metadata that you don't see on the screenshot of the newly uploaded mp3 above: 
<img width="412" alt="Screen Shot 2019-07-16 at 4 54 09 PM" src="https://user-images.githubusercontent.com/210024/61331267-9deba800-a7ef-11e9-9077-b1e2ea305459.png">

And here's a screenshot of the missing duration (ignore the date recorded field I accidentally circled) in the Seriously Simple Podcasting plugin after selecting the file and saving. 
<img width="623" alt="Screen Shot 2019-07-16 at 4 58 50 PM" src="https://user-images.githubusercontent.com/210024/61331366-d7bcae80-a7ef-11e9-8c5a-a9ecae0c4133.png">

It seems like some sort of file processing is not being allowed to happen on upload or when the file is selected from the media library by another plugin. 

Any ideas?

**Comment by jawngee** [comment]
Are you using direct uploads?

**Comment by jawngee** [comment]
I've tested and direct uploads is the only scenario where file size and the audio properties are not populated, which makes sense because WordPress never touches the file as it's directly uploaded to S3 or whatever cloud storage service you are using.

**Comment by jawngee** [comment]
Actually, strike that, it also happens if you have delete uploads enabled.

**Comment by jawngee** [comment]
I've fixed in 3.x that is coming out in the next couple of days, if you want to test it sooner, email me at jon@interfacelab.com
