### ISSUE TITLE
Google Cloud Upload image meta getting stored without https:// prefix

### ISSUE THREAD

**Issue by jeryj** [Interfacelab/ilab-media-tools#91]
When uploading images with Imgix off, the image meta is storing the image path as `storage.googleapis.com` in `classes/Storage/Driver/GoogleCloud/GoogleStorage.php`. Thus, since the `https://` is missing, the image paths are not found because they're looking relative to the site url.

Changing all the lines in `GoogleStorage.php` from:
`$url = str_replace('gs://',StorageObject::DEFAULT_DOWNLOAD_URL.'/', $url);`
to
`$url = str_replace('gs://','https://'.StorageObject::DEFAULT_DOWNLOAD_URL.'/', $url);` 
fixed the issue for me, but I don't know if this causes a separate bug.

### Reproduction
1. Set-up Google Cloud Storage but do not have imgix on.
2. Upload an image
3. The image thumbnail will not be there, and it's image meta will all be stored as `storage.googleapis.com/..`

### What Should Happen
The image paths should end up with an `http` prefix of some kind, like `https://` so the browser isn't trying to find them relative to the current site.

**Comment by jawngee** [comment]
What version of the plugin are you using?  There's no line, in the current version, like:

`$url = str_replace('gs://',StorageObject::DEFAULT_DOWNLOAD_URL.'/', $url);`

In the current version it looks like:

`$url = str_replace('gs://',static::defaultDownloadUrl().'/', $url);`

And the `static::defaultDownloadUrl()` looks like:

```php
	public static function defaultDownloadUrl() {
		$url = StorageObject::DEFAULT_DOWNLOAD_URL;
		if (!filter_var($url, FILTER_VALIDATE_URL)) {
			$url = 'https://'.$url;
		}

		return $url;
	}
```

**Comment by jawngee** [comment]
And it ends up that `StorageObject::DEFAULT_DOWNLOAD_URL` is a huge misnomer because it returns a host and not an actual url.

**Comment by jeryj** [comment]
Ah - my bad. I had been using 3.0.7. I should have checked that first. The current github version (3.1.4) one is working for me! 

I did notice that some of the lines have the `https://` appended before the `defaultDownloadUrl`. It doesn't seem to cause any issues though... Like on line 381 in `GoogleStorage.php`.

`$url = str_replace('gs://','https://'.static::defaultDownloadUrl().'/', $url);`

Thanks for having already fixed this and letting me know! Cheers!
