### ISSUE TITLE
Error . The actual error was: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by hmpargi** [Interfacelab/ilab-media-tools#92]
I am continuously receiving this error. Please can you help me debug.

There was an error attempting to run your batch. Try changing the Connection Timeout in Storage Settings to a higher number like 0.1 or 1 to see if that helps. The actual error was: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received

THanks,
hp

**Comment by hmpargi** [comment]
Also when i click Settings to navigation to change this numbers i get . . The actual error was: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received

I have change 0.01 to 0.1 inside batch-processing.config.php directly through plugin, but this didnt help me either.

**Comment by hmpargi** [comment]
How do i disable SSL check 
		"mcloud-storage-batch-verify-ssl" => [
						"title" => "Verify SSL",
						"description" => "Determines if SSL is verified when making the remote connection for the background process.",
						"type" => "select",
						"default" => "none",
						"options" => [
							"default" => "System Default",
							"yes" => "Yes",
							"no" => "No",
						]

It also says please disable SSL when i ran system check test, Because i am not able to settings. any fixes?

**Comment by jawngee** [comment]
You need to run the system test:

![Media Cloud Tools ‹ mediacloud test — WordPress 2019-08-18 23-14-55](https://user-images.githubusercontent.com/44449/63227171-0b835d80-c20e-11e9-8c97-4a40cb6d694c.png)

It will automatically adjust your settings to get something working.

I'm guessing you are some c-panel based VPS managed hosting deal.

**Comment by hmpargi** [comment]
I did test and i received 
this results.
https://i.imgur.com/GT5qNFh.png

**Comment by jawngee** [comment]
Go to the batch processing settings:

![Monosnap 2019-08-18 23-23-29](https://user-images.githubusercontent.com/44449/63227319-4043e480-c20f-11e9-9936-74852d41952b.png)

In the batch settings, try this first:

- Verify SSL to NO
- Connection Timeout is blank
- Timeout is 0.1
- Skip DNS is turned off

**Comment by jawngee** [comment]
If those settings don't work, then just turn off "Process in Background" because your server setup is a mess.  If Process in Background is turned off, you will have to leave the browser window open when running any batch tool because it uses ajax in the browser.

I'm going to close this because it isn't a bug, it's a tech support issue.

If you still have problems open up a topic on https://talk.mediacloud.press/
