### ISSUE TITLE
Google cloud storage - don't use ACL settings

### ISSUE THREAD

**Issue by wmuizelaar** [Interfacelab/ilab-media-tools#93]
Hi,

Thanks for this great plugin! These days, google cloud storage can be used with IAM policies only, without the ACL subsystem. See https://cloud.google.com/storage/docs/bucket-policy-only for more details.

Would it be possible to have the usage of this system also implemented in the ilab-media-tools plugin?

Thanks, regards,

Wietse

**Comment by jawngee** [comment]
You can still use ACL, it's still an option when you create a bucket.  It'll be awhile before we implement this.

**Comment by wmuizelaar** [comment]
True - although there are now also possibilities to restrict the usage of ACLs on organizational policy level.

I could give a PR a try for this as an optional feature?

**Comment by jawngee** [comment]
Yes would love it, thanks!
